name: simple_date_range_picker
description: A simple, stylish date picker component for Flutter.
version: 1.0.0
homepage: "https://www.github.com/andyhorn/simple_date_range_picker"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
