name: simple_date_range_picker
description: A simple, stylish date range picker component for Flutter.
version: 0.0.3
homepage: "https://www.github.com/andyhorn/simple_date_range_picker"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
